# Generated by Django 2.2.12 on 2020-05-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
